Now writing all errors to stderr

diff --git a/ssh-to b/ssh-to
--- a/ssh-to
+++ b/ssh-to
@@ -166,9 +166,9 @@ then
 		RESULT=$?
 		if test $RESULT -ne 0
 		then
-			echo "! "
-			echo "! Editor '$EDITOR' exited with status '$RESULT', stopping."
-			echo "! "
+			>&2 echo "! "
+			>&2 echo "! Editor '$EDITOR' exited with status '$RESULT', stopping."
+			>&2 echo "! "
 			rm -f $TMP
 			exit 1
 		fi
@@ -182,14 +182,14 @@ then
 			break
 		fi
 
-		echo "! "
-		echo "! Sorry, but there was a JSON parsing error:"
-		echo "! "
-		echo -n "!	"
+		>&2 echo "! "
+		>&2 echo "! Sorry, but there was a JSON parsing error:"
+		>&2 echo "! "
+		>&2 echo -n "!	"
 		cat $TMP | jq . >/dev/null || true
-		echo "! "
-		echo "! Press ENTER to continue, or ctrl-C to exit. "
-		echo "! "
+		>&2 echo "! "
+		>&2 echo "! Press ENTER to continue, or ctrl-C to exit. "
+		>&2 echo "! "
 		read
 
 	done
