Errors should really be written to JSON

diff --git a/ssh-to b/ssh-to
--- a/ssh-to
+++ b/ssh-to
@@ -40,22 +40,22 @@ LOOP=""
 JQ=$(which jq || true)
 if test ! "$JQ"
 then
-	echo "! "
-	echo "! jq does not seem to be installed on the system!"
-	echo "! "
-	echo "! You must install jq in order to use $0"
-	echo "! "
-	echo "! Depending on your OS, it may be one of the following commands:"
-	echo "! "
-	echo "! 	yum install jq"
-	echo "! 	apt-get install jq"
-	echo "! 	brew install jq"
-	echo "! "
-	echo "! jq can also be downloaded from: "
-	echo "! "
-	echo "! 	https://stedolan.github.io/jq/"
-	echo "! "
-	echo "! "
+	>&2 echo "! "
+	>&2 echo "! jq does not seem to be installed on the system!"
+	>&2 echo "! "
+	>&2 echo "! You must install jq in order to use $0"
+	>&2 echo "! "
+	>&2 echo "! Depending on your OS, it may be one of the following commands:"
+	>&2 echo "! "
+	>&2 echo "! 	yum install jq"
+	>&2 echo "! 	apt-get install jq"
+	>&2 echo "! 	brew install jq"
+	>&2 echo "! "
+	>&2 echo "! jq can also be downloaded from: "
+	>&2 echo "! "
+	>&2 echo "! 	https://stedolan.github.io/jq/"
+	>&2 echo "! "
+	>&2 echo "! "
 	exit 1
 fi
 
@@ -75,9 +75,9 @@ then
 
 	if test -f "$FILE0"
 	then
-		echo "! "
-		echo "! Error: File '$FILE0' already exists, cannot run --create!"
-		echo "! "
+		>&2 echo "! "
+		>&2 echo "! Error: File '$FILE0' already exists, cannot run --create!"
+		>&2 echo "! "
 		exit 1
 	fi
 
@@ -122,18 +122,18 @@ then
 		FILE=$FILE2
 		if test ! -f "$FILE2"
 		then
-			echo "! "
-			echo "! Unable to read from file '$FILE0, '$FILE1' *or* '$FILE2'"
-			echo "! "
-			echo "! If you'd like to create a sample json.servers file, please run: "
-			echo "! "
-			echo "! 	ssh-to --create "
-			echo "! "
-			echo "! "
-			echo "! To view more info or file a bug, please visit the project GitHub: "
-			echo "!		https://github.com/Comcast/ssh-to"
-			echo "! "
-			echo "! "
+			>&2 echo "! "
+			>&2 echo "! Unable to read from file '$FILE0, '$FILE1' *or* '$FILE2'"
+			>&2 echo "! "
+			>&2 echo "! If you'd like to create a sample json.servers file, please run: "
+			>&2 echo "! "
+			>&2 echo "! 	ssh-to --create "
+			>&2 echo "! "
+			>&2 echo "! "
+			>&2 echo "! To view more info or file a bug, please visit the project GitHub: "
+			>&2 echo "!		https://github.com/Comcast/ssh-to"
+			>&2 echo "! "
+			>&2 echo "! "
 			exit 1
 		fi
 	fi
